### ISSUE TITLE
IOS vs Windows Appearance issues

### ISSUE THREAD

**Issue by Callingrapher** [Callingrapher/ProjectTheFirst#8]
When sending code back and form via Slack, Imani and I had display issues between two different operating systems.  I'm wondering if this will cause any problems when code is pulled in future.  Leaving this ticket open for a while to see.

**Comment by nhounhou** [comment]
We had the same issue with Samantha, when we called the Store Locator 
API, the code is working in my system (Windows), while she's having error code on hers (IOS)

**Comment by Callingrapher** [comment]
Added a reset CSS file.  Problem seems to be solved.
